### ISSUE TITLE
Chinese Translation Update For Pliers 2021

### ISSUE THREAD

**Issue by Ventulus-lab** [MateuszBogdan/OniPliers#2]
Hi，
I'm glad you fixed Plier's errand feature.
There was actually a mistake in the original Chinese translation file.
So this time it was fixed and a translation of the new strings about errand in your mod was added.
I hope you will adopt it!
[zh.zip](https://github.com/MateuszBogdan/OniPliers/files/7943614/zh.zip)

**Comment by Ventulus-lab** [comment]
BTW, I have found one possible problem.
It is that with Pliers2021 enabled, the translation of the module option settings provided by PLib will not work. For example, the "Options 选项" changes back to English, etc.
I have no idea why this is happening, but I am sure it is caused by Pliers2021.

**Comment by MateuszBogdan** [comment]
Hi,

Thank you for translation files and bug report. I will adpot newer
translation in next release. I plan to release new verion in a few days.
Currently there is a bug in Pliers Errand mode that sometimes crash the
game. Unfortunately fix is not that obious and I have very little spare
time for mod development.
I will try to look into the options translation bug, i guess its probably
because my mod is reusing some localized string name as other mods
(possible bug from code copy paste).

Expect translation to be included in upcoming version.

**Comment by VentulusCN** [comment]
I am very sorry that the "the options translation bug" was a misunderstanding. It was not caused by "Pliers 2021", so I deleted that comment.

**Comment by MateuszBogdan** [comment]
Updated in version 1.1.2
